# Generated by Django 3.0.4 on 2023-08-23 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comodo', '0003_auto_20230822_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioComodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridade', models.CharField(choices=[('SIM', 'Sim'), ('NÃO', 'Não')], help_text='* Campos obrigatórios', max_length=3, verbose_name='Usuário tem prioridade neste cômodo *')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Hash')),
                ('comodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comodo', to='comodo.Comodo', verbose_name='Cômodo associado a este usuário *')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuário ou pessoa para cômodo *')),
            ],
            options={
                'verbose_name': 'UsuarioComodo',
                'verbose_name_plural': 'UsuarioComodos',
                'ordering': ['-is_active', 'usuario', 'comodo'],
            },
        ),
    ]
