# Generated by Django 3.0.4 on 2023-08-23 18:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comodo', '0003_auto_20230822_1443'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuariocomodo', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usuariocomodo',
            unique_together={('usuario', 'comodo')},
        ),
    ]
