# Generated by Django 3.0.4 on 2023-08-23 18:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comodo', '0003_auto_20230822_1443'),
        ('usuariocomodo', '0002_auto_20230823_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariocomodo',
            name='lugar',
            field=models.CharField(help_text='Por exemplo, Casa da Praia ou Escritório ou Apartamento na Praia', max_length=30, null=True, verbose_name='Localização deste cômodo *'),
        ),
        migrations.AlterUniqueTogether(
            name='usuariocomodo',
            unique_together={('usuario', 'comodo', 'lugar')},
        ),
    ]
