# Generated by Django 3.0.4 on 2023-08-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuariocomodo', '0003_auto_20230823_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariocomodo',
            name='cidade',
            field=models.CharField(max_length=30, null=True, verbose_name='Cidade *'),
        ),
        migrations.AlterField(
            model_name='usuariocomodo',
            name='lugar',
            field=models.CharField(choices=[('APARTAMENTO', 'APARTAMENTO'), ('CASA', 'Casa'), ('CONSULTÓRIO', 'Consultório'), ('ESCRITÓRIO', 'Escritório'), ('SÍTIO', 'Sítio'), ('OUTRO', 'Outro')], max_length=12, null=True, verbose_name='Localização deste cômodo *'),
        ),
    ]
