# Generated by Django 3.0.4 on 2023-08-30 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuariocomodo', '0006_auto_20230829_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariocomodo',
            name='inverno_iluminacao_manha',
            field=models.CharField(blank=True, choices=[('FORTE', 'Forte'), ('MÉDIO', 'Médio'), ('FRACO', 'Fraco')], max_length=5, null=True, verbose_name='Itensidade da iluminação'),
        ),
        migrations.AddField(
            model_name='usuariocomodo',
            name='inverno_iluminacao_noite',
            field=models.CharField(blank=True, choices=[('FORTE', 'Forte'), ('MÉDIO', 'Médio'), ('FRACO', 'Fraco')], max_length=5, null=True, verbose_name='Itensidade da iluminação'),
        ),
        migrations.AddField(
            model_name='usuariocomodo',
            name='inverno_iluminacao_tarde',
            field=models.CharField(blank=True, choices=[('FORTE', 'Forte'), ('MÉDIO', 'Médio'), ('FRACO', 'Fraco')], max_length=5, null=True, verbose_name='Itensidade da iluminação'),
        ),
        migrations.AddField(
            model_name='usuariocomodo',
            name='outono_iluminacao_manha',
            field=models.CharField(blank=True, choices=[('FORTE', 'Forte'), ('MÉDIO', 'Médio'), ('FRACO', 'Fraco')], max_length=5, null=True, verbose_name='Itensidade da iluminação'),
        ),
        migrations.AddField(
            model_name='usuariocomodo',
            name='outono_iluminacao_noite',
            field=models.CharField(blank=True, choices=[('FORTE', 'Forte'), ('MÉDIO', 'Médio'), ('FRACO', 'Fraco')], max_length=5, null=True, verbose_name='Itensidade da iluminação'),
        ),
        migrations.AddField(
            model_name='usuariocomodo',
            name='outono_iluminacao_tarde',
            field=models.CharField(blank=True, choices=[('FORTE', 'Forte'), ('MÉDIO', 'Médio'), ('FRACO', 'Fraco')], max_length=5, null=True, verbose_name='Itensidade da iluminação'),
        ),
        migrations.AddField(
            model_name='usuariocomodo',
            name='primavera_iluminacao_manha',
            field=models.CharField(blank=True, choices=[('FORTE', 'Forte'), ('MÉDIO', 'Médio'), ('FRACO', 'Fraco')], max_length=5, null=True, verbose_name='Itensidade da iluminação'),
        ),
        migrations.AddField(
            model_name='usuariocomodo',
            name='primavera_iluminacao_noite',
            field=models.CharField(blank=True, choices=[('FORTE', 'Forte'), ('MÉDIO', 'Médio'), ('FRACO', 'Fraco')], max_length=5, null=True, verbose_name='Itensidade da iluminação'),
        ),
        migrations.AddField(
            model_name='usuariocomodo',
            name='primavera_iluminacao_tarde',
            field=models.CharField(blank=True, choices=[('FORTE', 'Forte'), ('MÉDIO', 'Médio'), ('FRACO', 'Fraco')], max_length=5, null=True, verbose_name='Itensidade da iluminação'),
        ),
        migrations.AddField(
            model_name='usuariocomodo',
            name='verao_iluminacao_manha',
            field=models.CharField(blank=True, choices=[('FORTE', 'Forte'), ('MÉDIO', 'Médio'), ('FRACO', 'Fraco')], max_length=5, null=True, verbose_name='Itensidade da iluminação'),
        ),
        migrations.AddField(
            model_name='usuariocomodo',
            name='verao_iluminacao_noite',
            field=models.CharField(blank=True, choices=[('FORTE', 'Forte'), ('MÉDIO', 'Médio'), ('FRACO', 'Fraco')], max_length=5, null=True, verbose_name='Itensidade da iluminação'),
        ),
        migrations.AddField(
            model_name='usuariocomodo',
            name='verao_iluminacao_tarde',
            field=models.CharField(blank=True, choices=[('FORTE', 'Forte'), ('MÉDIO', 'Médio'), ('FRACO', 'Fraco')], max_length=5, null=True, verbose_name='Itensidade da iluminação'),
        ),
    ]
