# Generated by Django 3.0.4 on 2023-09-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuariocomodo', '0008_auto_20230911_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariocomodo',
            name='crenca_webservice',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Base de crença convertida do banco para AgentSpeak(L) e Jason'),
        ),
    ]
