# Generated by Django 3.0.4 on 2023-09-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuariocomodo', '0009_usuariocomodo_crenca_webservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariocomodo',
            name='inverno_iluminacao_manha',
            field=models.CharField(blank=True, choices=[('FORTE', 'Forte'), ('MÉDIA', 'Médio'), ('FRACA', 'Fraco'), ('DESLIGADA', 'Desligada')], default='DESLIGADA', help_text='Itensidade da iluminação', max_length=10, null=True, verbose_name='Manhã'),
        ),
        migrations.AlterField(
            model_name='usuariocomodo',
            name='inverno_iluminacao_noite',
            field=models.CharField(blank=True, choices=[('FORTE', 'Forte'), ('MÉDIA', 'Médio'), ('FRACA', 'Fraco'), ('DESLIGADA', 'Desligada')], default='DESLIGADA', help_text='Itensidade da iluminação', max_length=10, null=True, verbose_name='Noite'),
        ),
        migrations.AlterField(
            model_name='usuariocomodo',
            name='inverno_iluminacao_tarde',
            field=models.CharField(blank=True, choices=[('FORTE', 'Forte'), ('MÉDIA', 'Médio'), ('FRACA', 'Fraco'), ('DESLIGADA', 'Desligada')], default='DESLIGADA', help_text='Itensidade da iluminação', max_length=10, null=True, verbose_name='Tarde'),
        ),
        migrations.AlterField(
            model_name='usuariocomodo',
            name='outono_iluminacao_manha',
            field=models.CharField(blank=True, choices=[('FORTE', 'Forte'), ('MÉDIA', 'Médio'), ('FRACA', 'Fraco'), ('DESLIGADA', 'Desligada')], default='DESLIGADA', help_text='Itensidade da iluminação', max_length=10, null=True, verbose_name='Manhã'),
        ),
        migrations.AlterField(
            model_name='usuariocomodo',
            name='outono_iluminacao_noite',
            field=models.CharField(blank=True, choices=[('FORTE', 'Forte'), ('MÉDIA', 'Médio'), ('FRACA', 'Fraco'), ('DESLIGADA', 'Desligada')], default='DESLIGADA', help_text='Itensidade da iluminação', max_length=10, null=True, verbose_name='Noite'),
        ),
        migrations.AlterField(
            model_name='usuariocomodo',
            name='outono_iluminacao_tarde',
            field=models.CharField(blank=True, choices=[('FORTE', 'Forte'), ('MÉDIA', 'Médio'), ('FRACA', 'Fraco'), ('DESLIGADA', 'Desligada')], default='DESLIGADA', help_text='Itensidade da iluminação', max_length=10, null=True, verbose_name='Tarde'),
        ),
        migrations.AlterField(
            model_name='usuariocomodo',
            name='primavera_iluminacao_manha',
            field=models.CharField(blank=True, choices=[('FORTE', 'Forte'), ('MÉDIA', 'Médio'), ('FRACA', 'Fraco'), ('DESLIGADA', 'Desligada')], default='DESLIGADA', help_text='Itensidade da iluminação', max_length=10, null=True, verbose_name='Manhã'),
        ),
        migrations.AlterField(
            model_name='usuariocomodo',
            name='primavera_iluminacao_noite',
            field=models.CharField(blank=True, choices=[('FORTE', 'Forte'), ('MÉDIA', 'Médio'), ('FRACA', 'Fraco'), ('DESLIGADA', 'Desligada')], default='DESLIGADA', help_text='Itensidade da iluminação', max_length=10, null=True, verbose_name='Noite'),
        ),
        migrations.AlterField(
            model_name='usuariocomodo',
            name='primavera_iluminacao_tarde',
            field=models.CharField(blank=True, choices=[('FORTE', 'Forte'), ('MÉDIA', 'Médio'), ('FRACA', 'Fraco'), ('DESLIGADA', 'Desligada')], default='DESLIGADA', help_text='Itensidade da iluminação', max_length=10, null=True, verbose_name='Tarde'),
        ),
        migrations.AlterField(
            model_name='usuariocomodo',
            name='verao_iluminacao_manha',
            field=models.CharField(blank=True, choices=[('FORTE', 'Forte'), ('MÉDIA', 'Médio'), ('FRACA', 'Fraco'), ('DESLIGADA', 'Desligada')], default='DESLIGADA', help_text='Itensidade da iluminação', max_length=10, null=True, verbose_name='Manhã: '),
        ),
        migrations.AlterField(
            model_name='usuariocomodo',
            name='verao_iluminacao_noite',
            field=models.CharField(blank=True, choices=[('FORTE', 'Forte'), ('MÉDIA', 'Médio'), ('FRACA', 'Fraco'), ('DESLIGADA', 'Desligada')], default='DESLIGADA', help_text='Itensidade da iluminação', max_length=10, null=True, verbose_name='Noite'),
        ),
        migrations.AlterField(
            model_name='usuariocomodo',
            name='verao_iluminacao_tarde',
            field=models.CharField(blank=True, choices=[('FORTE', 'Forte'), ('MÉDIA', 'Médio'), ('FRACA', 'Fraco'), ('DESLIGADA', 'Desligada')], default='DESLIGADA', help_text='Itensidade da iluminação', max_length=10, null=True, verbose_name='Tarde'),
        ),
    ]
