# Generated by Django 3.0.4 on 2023-08-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text='Ar condicionado ou cafeteira ou sistema de iluminação.', max_length=20, verbose_name='Descrição do equipamento')),
                ('marca', models.CharField(max_length=30, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=30, verbose_name='Modelo')),
                ('tipo', models.CharField(choices=[('CLIMATIZAÇÃO', 'Climatização'), ('ILUMINAÇÃO', 'Iluminação')], help_text='* Campos obrigatórios', max_length=15, verbose_name='Tipo do equipamento *')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Hash')),
            ],
            options={
                'verbose_name': 'equipamento',
                'verbose_name_plural': 'equipamentos',
                'ordering': ['-is_active', 'descricao'],
            },
        ),
    ]
