# Generated by Django 3.0.4 on 2023-08-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='descricao',
            field=models.CharField(help_text='Ar condicionado ou cafeteira ou sistema de iluminação.', max_length=40, verbose_name='Descrição do equipamento'),
        ),
    ]
