# Generated by Django 3.0.4 on 2023-08-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamento', '0002_auto_20230822_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='observacao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Alguma observação ou detalhe do equipamento'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='modelo',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Modelo'),
        ),
    ]
