# Generated by Django 3.0.4 on 2023-08-23 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipamento', '0003_auto_20230822_1447'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipamento',
            options={'ordering': ['-is_active', 'tipo', 'descricao'], 'verbose_name': 'equipamento', 'verbose_name_plural': 'equipamentos'},
        ),
    ]
