# Generated by Django 3.0.4 on 2023-08-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comodo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comodo',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
