# Generated by Django 3.0.4 on 2023-08-22 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comodo', '0002_comodo_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comodo',
            options={'ordering': ['-is_active', 'descricao'], 'verbose_name': 'comodo', 'verbose_name_plural': 'comodos'},
        ),
    ]
