# Generated by Django 3.0.4 on 2023-08-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comodo', '0004_comodo_equipamentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='comodo',
            name='cidade',
            field=models.CharField(max_length=30, null=True, verbose_name='Cidade *'),
        ),
        migrations.AddField(
            model_name='comodo',
            name='lugar',
            field=models.CharField(choices=[('APARTAMENTO', 'Apartamento'), ('CASA', 'Casa'), ('CONSULTÓRIO', 'Consultório'), ('ESCRITÓRIO', 'Escritório'), ('SÍTIO', 'Sítio'), ('OUTRO', 'Outro')], max_length=12, null=True, verbose_name='Localização deste cômodo *'),
        ),
        migrations.AlterUniqueTogether(
            name='comodo',
            unique_together={('descricao', 'lugar', 'cidade')},
        ),
    ]
